-d D:\AWORK\04_Archives\SOFT\fpga\tangnano4k\empu_uart\impl\gwsynthesis\cm3_demo.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\AWORK\04_Archives\SOFT\fpga\tangnano4k\empu_uart\src\cm3_demo.cst
-cfg D:\AWORK\04_Archives\SOFT\fpga\tangnano4k\empu_uart\impl\pnr\device.cfg
-sdc D:\AWORK\04_Archives\SOFT\fpga\tangnano4k\empu_uart\src\cm3_demo.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
